# Generated by Django 2.2.5 on 2020-09-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacer', models.IntegerField(blank=True, null=True)),
                ('longTimeRun', models.IntegerField(blank=True, null=True)),
                ('stepTest', models.IntegerField(blank=True, null=True)),
                ('bendFoward', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('totalFlexibility', models.IntegerField(blank=True, null=True)),
                ('pushUp', models.IntegerField(blank=True, null=True)),
                ('sitUp', models.IntegerField(blank=True, null=True)),
                ('grip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sprint', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('longJump', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stats',
            },
        ),
    ]
